### ISSUE TITLE
LIMIT, ORDER, FILTER...

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/rdf-easy#3]
Hi @jeff-zucker  please could you tell me if "LIMIT, ORDER, FILTER..." functionnalities implemented ? 

```
    const inbox = "https://agora.solid.community/public/agora/inbox/"

  let files = await this.rdf.query( inbox, `SELECT ?url ?mtime WHERE {
    <> ldp:contains ?url.
    ?url stat:mtime ?mtime.
    FILTER {
      ?mtime > 1587800000
    }
  }

  `)

  console.log(files.length)
  for(var f of files){ console.log(f.url, f.mtime) }
```

or 
```
  let files = await this.rdf.query( inbox, `SELECT ?url WHERE {
    <> ldp:contains ?url.
    LIMIT 2
  }

  `)

  console.log(files.length)
  for(var f of files){ console.log(f.url) }
```

return all 56 url present in the folder ?? 
Or is it server side that the endpoint does not carry about it ?
Thxs .

**Comment by jeff-zucker** [comment]
There is no server-side SPARQL processing of select queries in Solid.  None.  Solid servers recognize SPARQL delete and insert, but not select  or describe or anything that asks questions.

All SPARQL processing in rdf-easy is done on the client side via rdflib so the dialect of  SPARQL is determined by rdflib.js, not by rdf-easy.  Rdflib.js is NOT a complete implementation of SPARQL.  I have plans to make a version of rdf-easy that uses Communica, a more complete SPARQL engine, but it will be a while before I implement that.  I believe (but it's worth checking in the code) that LIMIT and FILTER and ORDER are not supported in rdflib.

> return all 56 url present in the folder

That is because rdflib apparently doesn't implement LIMIT.  But even if it  did, all records will be returned from the server anyway.   As I said above, there is NO server-side processing of SPARQL (this is a specific decision of the specification writers who say they will never add server-side SPARQL as  part of the spec although servers may implement it independently eventually).   So this means that regardless of what SPARQL engine or query you use, you will *always* be retrieving the entire document from the server.  The question is what happens to it once you have the document.  You could, if rdflib supported LIMIT add that to the SPARQL or you could simply do it in Javascript - a splice on the resultset or break out of a loop through the result set.  The Javascript will actually be *faster* than the SPARQL since a SPARQL command would need to be parsed and then would do its own splice or loop.  

So while using LIMIT and ORDER in SPARQL are "cleaner" looking code, given that none of it is implemented on the server, there is no reason you should not just do it in Javascript.

Feel free to ask questions if I've been unclear.

**Comment by scenaristeur** [comment]
ok, i just wanted to not retrieve all the folder and select / filter before getting all the files . 
thxs

**Comment by jeff-zucker** [comment]
Maybe I need to clarify.  When you query the folder, you only query the one file for the container, and it has the names and dates of the contained files.  That is the query you are limiting.  If you later go back and get some of those files, it would be a second trip but to read the folder, there is only one read regardless of the number of files in it.
